#Advanced pickit to specify atributes that needs to be matched to stash items
#All items needs to be selected in the pickit.ini
#To use a any value just use 0
#The following attributes are supported
#sockets [0,1,2,3,4,5,6]
#Life [0, 20]
#life_stolen [0]
#Mana [0]
#mana_stolen [0]
#Attackrating [0, 20]
#increased_attack_speed [0, 15, 20]
#magicfind [0, 7]
#maximum_damage [0, 3]
#all_resist [0, 5, 40, 45]
#lightning_resist [0]
#fire_resist [0]
#cold_resist [0]
#strenght [0]
#dexterity [0]
#faster_cast_rate [0]
#enhanced damage [0, 15]
#enhanced_defense [0, 15]
#sorceress_skills [2, 3]
#all_skills [0, 1, 2]
#javalin_spears [0, 2]
#fire_absorb [15]
#cannot_be_frozen [1]
#blessed_hammer [3]
#bone_spear [3]
#bone_spirit [3]
#bow_skills [3]
#chilling_armor [3]
#concentration [3]
#conviction [3]
#energy_shield [3]
#fanaticism [3]
#fist_of_the_heavens [3]
#holy_shield [3]
#lightning_sentry [3]
#shiver_armor [3]
#thunder_storm [3]
#tornado [3]
#venom [3]
#warcries [3]
#zeal [3]
#ethereal [0, 1] 0 = non ethereal, 1 = ethereal
#Amazonskiller [1] #All Skiller GCs for Amazon
#Assasinskiller [1] #All Skiller GCs for Assasin
#Barbarianskiller [1] #All Skiller GCs for Barbarian 
#Druidskiller [1] #All Skiller GCs for Druid
#Necromancerskiller [1] #All Skiller GCs for Necromancer
#Paladinskiller [1] #All Skiller GCs for Paladin
#Sorceressskiller [1] #All Skiller GCs for Sorceress
#==================================================================#
#<<<<<<<<<<<<<<<<<<<<<<<<<< MAGIC ITEMS >>>>>>>>>>>>>>>>>>>>>>>>>>>#
#==================================================================#
#shields
magics:
- magic_monarch:
  sockets: 4
  ethereal: 0

#small_charms
- magic_small_charm:
  magicfind: 7

- magic_small_charm:
  Life: 20

- magic_small_charm:
  maximum_damage: 3
  attack_rating: 20

- magic_small_charm:
  all_resist: 5

- magic_small_charm:
  Life: 0
  Mana: 0

#grand_charms
- magic_grand_charm:
  Amazonskiller: 1
- magic_grand_charm:
  Assasinskiller: 1
- magic_grand_charm:
  Barbarianskiller: 1
- magic_grand_charm:
  Druidskiller: 1
- magic_grand_charm:
  Necromancerskiller: 1
- magic_grand_charm:
  Paladinskiller: 1
- magic_grand_charm:
  Sorceressskiller: 1

#jewels
- magic_jewel:
  increased_attack_speed: 15

- magic_jewel:
  enhanced_damage: 0

#circlets
- magic_circlet:
  ethereal: 0
- magic_coronet:
  ethereal: 0
- magic_diadem:
  ethereal: 0
- magic_tiara:
  ethereal: 0
  
#==================================================================#
#<<<<<<<<<<<<<<<<<<<<<<<<<<<< UNIQUES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>#
#==================================================================#
uniques:
- uniq_weapon_eschuta_temper:
  sorceress_skills: 3

#soj, Bul Kathos
- uniq_misc_rings:
  all_skills: 1

#Dwarfstar
- uniq_misc_rings:
  fire_absorb: 15

#Ravenfrost
- uniq_misc_rings:
  cannot_be_frozen: 1

#Nagelring
- uniq_misc_rings:
  magicfind: 0


#==================================================================#
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< SETS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>#
#==================================================================#
- set_misc_amulets:
  sorceress_skills: 2

#==================================================================#
#<<<<<<<<<<<<<<<<<<<<<<<<<<< RARE ITEMS >>>>>>>>>>>>>>>>>>>>>>>>>>>#
#==================================================================#
rares:

#---------------------------------------#
#============== RARE RINGS =============#
#---------------------------------------#
#dual leech ring
- rare_ring:
  life_stolen: 0
  mana_stolen: 0

#fcr ring
- rare_ring:
  faster_cast_rate: 0

#---------------------------------------#
#============== RARE BELTS =============#
#---------------------------------------#
#exceptional rare belts
- rare_demonhide_sash:
  ethereal: 0
- rare_sharkskin_belt:
  ethereal: 0
- rare_mesh_belt:
  ethereal: 0
- rare_battle_belt:
  ethereal: 0
- rare_war_belt:
  ethereal: 0

#elite rare belts
- rare_spiderweb_sash:
  ethereal: 0
- rare_vampirefang_belt:
  ethereal: 0
- rare_mithril_coil:
  ethereal: 0
- rare_troll_belt:
  ethereal: 0
- rare_colossus_girdle:
  ethereal: 0

#---------------------------------------#
#============== RARE BOOTS =============#
#---------------------------------------#
#normal rare boots
- rare_greaves:
  ethereal: 0
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
- rare_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_chain_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_light_plated_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_heavy_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0

#exceptional rare boots
- rare_war_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_battle_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_mesh_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_sharkskin_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_demonhide_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0

#elite rare boots
- rare_myrmidon_greaves:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_mirrored_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_boneweave_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_scarabshell_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0
- rare_wyrmhide_boots:
  lightning_resist: 0
  fire_resist: 0
  cold_resist: 0
  ethereal: 0

#---------------------------------------#
#============= RARE GLOVES =============#
#---------------------------------------#

#normal rare gloves
- rare_leather_gloves:
  increased_attack_speed: 20
  javalin_spears: 2

- rare_heavy_gloves:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_chain_gloves:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_light_gauntlets:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_gauntlets:
  increased_attack_speed: 20
  javalin_spears: 2

#exceptional rare gloves
- rare_demonhide_gloves:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_sharkskin_gloves:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_heavy_bracers:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_battle_gauntlets:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_war_gauntlets:
  increased_attack_speed: 20
  javalin_spears: 2

#elite rare gloves
- rare_bramble_mitts:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_vampirebone_gloves:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_vambraces:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_crusader_gauntlets:
  increased_attack_speed: 20
  javalin_spears: 2
- rare_ogre_gauntlets:
  increased_attack_speed: 20
  javalin_spears: 2

