#Advanced pickit to specify atributes that needs to be matched to stash items
#All items needs to be selected in the pickit.ini
#To use a any value just use 0
#The following attributes are supported
#sockets [0,1,2,3,4,5,6]
#Life [0, 20]
#Attackrating [0, 20]
#magicfind [0, 7]
#maximum_damage [0, 3]
#all_resist [0, 5, 40, 45]
#strenght [0]
#dexterity [0]
#faster_cast_rate [0]
#enhanced damage [0, 15]
#enhanced_defense [0, 15]
#blessed_hammer [3]
#bone_spear [3]
#bone_spirit [3]
#bow_skills [3]
#chilling_armor [3]
#concentration [3]
#conviction [3]
#energy_shield [3]
#fanaticism [3]
#fist_of_the_heavens [3]
#holy_shield [3]
#lightning_sentry [3]
#shiver_armor [3]
#thunder_storm [3]
#tornado [3]
#venom [3]
#warcries [3]
#zeal [3]
#ethereal [0, 1] 0 = non ethereal, 1 = ethereal
#==================================================================#
#<<<<<<<<<<<<<<<<<<<<<<<<<< MAGIC ITEMS >>>>>>>>>>>>>>>>>>>>>>>>>>>#
#==================================================================#
magics:
- magic_monarch:
  sockets: 4
  ethereal: 0

- magic_small_charm:
  magicfind: 7

- magic_small_charm:
  Life: 20

- magic_small_charm:
  maximum_damage: 3
  attack_rating: 20

- magic_small_charm:
  all_resist: 5

- magic_grand_charm:
  Life: 20

- magic_circlet:
  ethereal: 0
- magic_coronet:
  ethereal: 0
- magic_diadem:
  ethereal: 0
- magic_tiara:
  ethereal: 0
  
#==================================================================#
#<<<<<<<<<<<<<<<<<<<<<<<<<<<< UNIQUES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>#
#==================================================================#
uniques:
- uniq_weapon_eschuta_temper:
  sorceress_skills: 3
  lightning_damage: 15

- uniq_weapon_eschuta_temper:
  sorceress_skills: 2

#==================================================================#
#<<<<<<<<<<<<<<<<<<<<<<<<<<< RARE ITEMS >>>>>>>>>>>>>>>>>>>>>>>>>>>#
#==================================================================#
rares:
- rare_circlet:
  ethereal: 1

#---------------------------------------#
#============== RARE BELTS =============#
#---------------------------------------#
#exceptional rare belts
- rare_demonhide_sash:
  ethereal: 0
- rare_sharkskin_belt:
  ethereal: 0
- rare_mesh_belt:
  ethereal: 0
- rare_battle_belt:
  ethereal: 0
- rare_war_belt:
  ethereal: 0

#elite rare belts
- rare_spiderweb_sash:
  ethereal: 0
- rare_vampirefang_belt:
  ethereal: 0
- rare_mithril_coil:
  ethereal: 0
- rare_troll_belt:
  ethereal: 0
- rare_colossus_girdle:
  ethereal: 0

#---------------------------------------#
#============== RARE BOOTS =============#
#---------------------------------------#
#normal rare boots
- rare_greaves:
  ethereal: 0
- rare_boots:
  ethereal: 0
- rare_chain_boots:
  ethereal: 0
- rare_light_plated_boots:
  ethereal: 0
- rare_heavy_boots:
  ethereal: 0

#exceptional rare boots
- rare_war_boots:
  ethereal: 0
- rare_battle_boots:
  ethereal: 0
- rare_mesh_boots:
  ethereal: 0
- rare_sharkskin_boots:
  ethereal: 0
- rare_demonhide_boots:
  ethereal: 0

#elite rare boots
- rare_myrmidon_greaves:
  ethereal: 0
- rare_mirrored_boots:
  ethereal: 0
- rare_boneweave_boots:
  ethereal: 0
- rare_scarabshell_boots:
  ethereal: 0
- rare_wyrmhide_boots:
  ethereal: 0

#---------------------------------------#
#============= RARE GLOVES =============#
#---------------------------------------#

#normal rare gloves
- rare_leather_gloves:
  ethereal: 0
- rare_heavy_gloves:
  ethereal: 0
- rare_chain_gloves:
  ethereal: 0
- rare_light_gauntlets:
  ethereal: 0
- rare_gauntlets:
  ethereal: 0

#exceptional rare gloves
- rare_demonhide_gloves:
  ethereal: 0
- rare_sharkskin_gloves:
  ethereal: 0
- rare_heavy_bracers:
  ethereal: 0
- rare_battle_gauntlets:
  ethereal: 0
- rare_war_gauntlets:
  ethereal: 0

#elite rare gloves
- rare_bramble_mitts:
  ethereal: 0
- rare_vampirebone_gloves:
  ethereal: 0
- rare_vambraces:
  ethereal: 0
- rare_crusader_gauntlets:
  ethereal: 0
- rare_ogre_gauntlets:
  ethereal: 0

